name: Bump Version

on:
  workflow_call:
    inputs:
      crate-version:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      crate-version:
        description: "Bump version: (e.g. -> 3.1.4-alpha+159)"
        required: true
        type: string

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - uses: actions/checkout@v4

      - run: git pull

      - name: Install cargo-bump
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-bump

      - name: Run cargo bump
        run: cargo bump ${{ inputs.crate-version }}

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Bump version: ${{ inputs.crate-version }}"
