name: Clean Cache

permissions:
  actions: write

on:
  workflow_dispatch:

jobs:
  clean-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: gh cache delete --all
        env:
          GH_TOKEN: ${{ github.token }}
