# Check for licenses and advisores
# ../../deny.toml
name: Cargo deny

on:
  workflow_call:
  workflow_dispatch:

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Cargo deny
        uses: EmbarkStudios/cargo-deny-action@v1

  cargo-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-audit

      - run: cargo audit
