name: Cargo If Lib

on:
  workflow_call:
    outputs:
      is_lib:
        value: ${{ jobs.check-if-lib.outputs.is_lib }}

jobs:
  check-if-lib:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install jql
        uses: taiki-e/install-action@v2
        with:
          tool: jql

      - name: Searching for lib
        id: searching
        run: |
          result=$(cargo metadata --format-version=1 --no-deps | jql '"packages"|>"targets"<|[0]|>"kind"' | jql '..' -i);
          echo "targets=$result" >> "$GITHUB_OUTPUT";
          echo kind of targets $result;

      - name: print if skip cargo-semver-checks
        if: ${{ !contains(steps.searching.outputs.targets, 'lib') }}
        run: echo "cargo semver-check only works in libraries"

    outputs:
      is_lib: ${{ contains(steps.searching.outputs.targets, 'lib') }}
