name: Pre Release

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      update-msrv:
        type: boolean
  workflow_dispatch:
    inputs:
      version:
        description: "Bump version: (e.g. -> 3.1.4-alpha+159)"
        required: true
        type: string
      update-msrv:
        type: boolean

permissions:
  contents: write

jobs:
  run-ci:
    uses: ./.github/workflows/ci.yaml

  cargo-semver-checks:
    needs: run-ci
    uses: ./.github/workflows/cargo_semver_checks.yaml
    with:
      bump-version: ${{ inputs.version  }}

  add-notice:
    needs: run-ci
    uses: ./.github/workflows/add_notice.yaml
    with:
      commit_message: ${{  inputs.version }}

  bump-version:
    needs: [cargo-semver-checks]
    uses: ./.github/workflows/bump_version.yaml
    with:
      crate-version: ${{  inputs.version }}

  update-attribution:
    needs: [bump-version]
    uses: ./.github/workflows/update_attributions.yaml
    with:
      commit_message: ${{ inputs.version }}
